/* Generated By:JavaCC: Do not edit this line. ShaclRulesParserConstants.java */
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.seaborne.jena.shacl_rules.lang.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ShaclRulesParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int BOM = 9;
  /** RegularExpression Id. */
  int IRIref = 10;
  /** RegularExpression Id. */
  int PNAME_NS = 11;
  /** RegularExpression Id. */
  int PNAME_LN = 12;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 13;
  /** RegularExpression Id. */
  int VAR1 = 14;
  /** RegularExpression Id. */
  int VAR2 = 15;
  /** RegularExpression Id. */
  int LANG_DIR = 16;
  /** RegularExpression Id. */
  int A2Z = 17;
  /** RegularExpression Id. */
  int A2ZN = 18;
  /** RegularExpression Id. */
  int KW_A = 19;
  /** RegularExpression Id. */
  int RULE = 20;
  /** RegularExpression Id. */
  int THEN = 21;
  /** RegularExpression Id. */
  int RULE_INFER = 22;
  /** RegularExpression Id. */
  int DATA = 23;
  /** RegularExpression Id. */
  int BASE = 24;
  /** RegularExpression Id. */
  int PREFIX = 25;
  /** RegularExpression Id. */
  int VERSION = 26;
  /** RegularExpression Id. */
  int WHERE = 27;
  /** RegularExpression Id. */
  int BIND = 28;
  /** RegularExpression Id. */
  int AS = 29;
  /** RegularExpression Id. */
  int LET = 30;
  /** RegularExpression Id. */
  int ASSIGN = 31;
  /** RegularExpression Id. */
  int TRIPLE = 32;
  /** RegularExpression Id. */
  int IS_TRIPLE = 33;
  /** RegularExpression Id. */
  int SUBJECT = 34;
  /** RegularExpression Id. */
  int PREDICATE = 35;
  /** RegularExpression Id. */
  int OBJECT = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int FILTER = 38;
  /** RegularExpression Id. */
  int BOUND = 39;
  /** RegularExpression Id. */
  int COALESCE = 40;
  /** RegularExpression Id. */
  int IN = 41;
  /** RegularExpression Id. */
  int IF = 42;
  /** RegularExpression Id. */
  int BNODE = 43;
  /** RegularExpression Id. */
  int IRI = 44;
  /** RegularExpression Id. */
  int URI = 45;
  /** RegularExpression Id. */
  int STR = 46;
  /** RegularExpression Id. */
  int STRLANG = 47;
  /** RegularExpression Id. */
  int STRLANGDIR = 48;
  /** RegularExpression Id. */
  int STRDT = 49;
  /** RegularExpression Id. */
  int DTYPE = 50;
  /** RegularExpression Id. */
  int LANG = 51;
  /** RegularExpression Id. */
  int LANGMATCHES = 52;
  /** RegularExpression Id. */
  int LANGDIR = 53;
  /** RegularExpression Id. */
  int IS_URI = 54;
  /** RegularExpression Id. */
  int IS_IRI = 55;
  /** RegularExpression Id. */
  int IS_BLANK = 56;
  /** RegularExpression Id. */
  int IS_LITERAL = 57;
  /** RegularExpression Id. */
  int IS_NUMERIC = 58;
  /** RegularExpression Id. */
  int HAS_LANG = 59;
  /** RegularExpression Id. */
  int HAS_LANGDIR = 60;
  /** RegularExpression Id. */
  int REGEX = 61;
  /** RegularExpression Id. */
  int SAME_TERM = 62;
  /** RegularExpression Id. */
  int SAME_VALUE = 63;
  /** RegularExpression Id. */
  int RAND = 64;
  /** RegularExpression Id. */
  int ABS = 65;
  /** RegularExpression Id. */
  int CEIL = 66;
  /** RegularExpression Id. */
  int FLOOR = 67;
  /** RegularExpression Id. */
  int ROUND = 68;
  /** RegularExpression Id. */
  int CONCAT = 69;
  /** RegularExpression Id. */
  int SUBSTR = 70;
  /** RegularExpression Id. */
  int STRLEN = 71;
  /** RegularExpression Id. */
  int REPLACE = 72;
  /** RegularExpression Id. */
  int UCASE = 73;
  /** RegularExpression Id. */
  int LCASE = 74;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 75;
  /** RegularExpression Id. */
  int CONTAINS = 76;
  /** RegularExpression Id. */
  int STRSTARTS = 77;
  /** RegularExpression Id. */
  int STRENDS = 78;
  /** RegularExpression Id. */
  int STRBEFORE = 79;
  /** RegularExpression Id. */
  int STRAFTER = 80;
  /** RegularExpression Id. */
  int YEAR = 81;
  /** RegularExpression Id. */
  int MONTH = 82;
  /** RegularExpression Id. */
  int DAY = 83;
  /** RegularExpression Id. */
  int HOURS = 84;
  /** RegularExpression Id. */
  int MINUTES = 85;
  /** RegularExpression Id. */
  int SECONDS = 86;
  /** RegularExpression Id. */
  int TIMEZONE = 87;
  /** RegularExpression Id. */
  int TZ = 88;
  /** RegularExpression Id. */
  int NOW = 89;
  /** RegularExpression Id. */
  int UUID = 90;
  /** RegularExpression Id. */
  int STRUUID = 91;
  /** RegularExpression Id. */
  int MD5 = 92;
  /** RegularExpression Id. */
  int SHA1 = 93;
  /** RegularExpression Id. */
  int SHA224 = 94;
  /** RegularExpression Id. */
  int SHA256 = 95;
  /** RegularExpression Id. */
  int SHA384 = 96;
  /** RegularExpression Id. */
  int SHA512 = 97;
  /** RegularExpression Id. */
  int TRUE = 98;
  /** RegularExpression Id. */
  int FALSE = 99;
  /** RegularExpression Id. */
  int DIGITS = 100;
  /** RegularExpression Id. */
  int INTEGER = 101;
  /** RegularExpression Id. */
  int DECIMAL = 102;
  /** RegularExpression Id. */
  int DOUBLE = 103;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 104;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 105;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 106;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 107;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 108;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 109;
  /** RegularExpression Id. */
  int EXPONENT = 110;
  /** RegularExpression Id. */
  int QUOTE_3D = 111;
  /** RegularExpression Id. */
  int QUOTE_3S = 112;
  /** RegularExpression Id. */
  int ECHAR = 113;
  /** RegularExpression Id. */
  int UCHAR = 114;
  /** RegularExpression Id. */
  int UCHAR4 = 115;
  /** RegularExpression Id. */
  int UCHAR8 = 116;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 117;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 118;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 119;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 120;
  /** RegularExpression Id. */
  int LPAREN = 121;
  /** RegularExpression Id. */
  int RPAREN = 122;
  /** RegularExpression Id. */
  int NIL = 123;
  /** RegularExpression Id. */
  int LBRACE = 124;
  /** RegularExpression Id. */
  int RBRACE = 125;
  /** RegularExpression Id. */
  int LBRACKET = 126;
  /** RegularExpression Id. */
  int RBRACKET = 127;
  /** RegularExpression Id. */
  int ANON = 128;
  /** RegularExpression Id. */
  int SEMICOLON = 129;
  /** RegularExpression Id. */
  int COMMA = 130;
  /** RegularExpression Id. */
  int DOT = 131;
  /** RegularExpression Id. */
  int EQ = 132;
  /** RegularExpression Id. */
  int NE = 133;
  /** RegularExpression Id. */
  int GT = 134;
  /** RegularExpression Id. */
  int LT = 135;
  /** RegularExpression Id. */
  int LE = 136;
  /** RegularExpression Id. */
  int GE = 137;
  /** RegularExpression Id. */
  int L_TRIPLE = 138;
  /** RegularExpression Id. */
  int R_TRIPLE = 139;
  /** RegularExpression Id. */
  int LT2 = 140;
  /** RegularExpression Id. */
  int GT2 = 141;
  /** RegularExpression Id. */
  int L_ANN = 142;
  /** RegularExpression Id. */
  int R_ANN = 143;
  /** RegularExpression Id. */
  int TILDE = 144;
  /** RegularExpression Id. */
  int BANG = 145;
  /** RegularExpression Id. */
  int COLON = 146;
  /** RegularExpression Id. */
  int SC_OR = 147;
  /** RegularExpression Id. */
  int SC_AND = 148;
  /** RegularExpression Id. */
  int PLUS = 149;
  /** RegularExpression Id. */
  int MINUS = 150;
  /** RegularExpression Id. */
  int STAR = 151;
  /** RegularExpression Id. */
  int SLASH = 152;
  /** RegularExpression Id. */
  int DATATYPE = 153;
  /** RegularExpression Id. */
  int AT = 154;
  /** RegularExpression Id. */
  int VBAR = 155;
  /** RegularExpression Id. */
  int CARAT = 156;
  /** RegularExpression Id. */
  int FPATH = 157;
  /** RegularExpression Id. */
  int RPATH = 158;
  /** RegularExpression Id. */
  int QMARK = 159;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 160;
  /** RegularExpression Id. */
  int PN_CHARS_U = 161;
  /** RegularExpression Id. */
  int PN_CHARS = 162;
  /** RegularExpression Id. */
  int PN_PREFIX = 163;
  /** RegularExpression Id. */
  int PN_LOCAL = 164;
  /** RegularExpression Id. */
  int VARNAME = 165;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 166;
  /** RegularExpression Id. */
  int PLX = 167;
  /** RegularExpression Id. */
  int HEX = 168;
  /** RegularExpression Id. */
  int PERCENT = 169;
  /** RegularExpression Id. */
  int UNKNOWN = 170;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "\"\\ufeff\"",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANG_DIR>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"rule\"",
    "\"then\"",
    "\":-\"",
    "\"data\"",
    "\"base\"",
    "\"prefix\"",
    "\"version\"",
    "\"where\"",
    "\"bind\"",
    "\"as\"",
    "\"let\"",
    "\":=\"",
    "\"TRIPLE\"",
    "\"isTRIPLE\"",
    "\"SUBJECT\"",
    "\"PREDICATE\"",
    "\"OBJECT\"",
    "\"not\"",
    "\"filter\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"str\"",
    "\"strlang\"",
    "\"strlangdir\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"langdir\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"hasLang\"",
    "\"hasLangDir\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"sameValue\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"NOW\"",
    "\"UUID\"",
    "\"STRUUID\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA224\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"true\"",
    "\"false\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "<EXPONENT>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<<(\"",
    "\")>>\"",
    "\"<<\"",
    "\">>\"",
    "\"{|\"",
    "\"|}\"",
    "\"~\"",
    "\"!\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\"|\"",
    "\"^\"",
    "\"->\"",
    "\"<-\"",
    "\"?\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
